// Generated by https://quicktype.io

export interface GqlResponse {
    people: PeopleData;
}

export interface GqlPersonResponse {
    person: Person;
}

export interface PeopleData {
    count:    number;
    next:     string;
    previous: null;
    results:  Person[];
}

export interface Person {
    name:      string;
    height:    string;
    mass:      string;
    gender:    Gender;
    homeworld_name: string;
    url:       string;
}

export enum Gender {
    Female = "female",
    Male = "male",
    NA = "n/a",
}
